### ISSUE TITLE
Link issue under MacOS (lions)

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#17]
any command returns:
dyld: Symbol not found: _environ
  Referenced from: /Users/bereziat/NOBACKUP/miniconda/envs/heim/bin/../lib/libinrimage.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by dfroger** [comment]
The package was build on OS X 10.9, and is reported to not work on 10.7.

Missing symbol seems to be:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man7/environ.7.html

and is used in `src/inrimage/inr_zcat.c`

The solution may be to use _NSGetEnviron() routine, defined in 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.5.sdk/usr/include/crt_externs.h

Will try it soon, by providing a patch to inrimage in the conda recipe apply the change.

**Comment by dfroger** [comment]
This is fixed with https://github.com/dfroger/df-conda-recipe/commit/08f88516c37cf31efb35d266dfd1056611df4cc1

This require to update libinrimage from 4.6.5.1 to 4.6.5.2 (at least):

```
source activate <heimdali-env>
conda update libinrimage
```

**Comment by dfroger** [comment]
Note that the problem is when building the shared library libinrimage.dylib only. With the static library libinrimage.a, there is no problem.

The man says:

Shared libraries and bundles don't have direct access to environ, which is only available to the loader ld(1) when a complete program is being linked.  The environment routines can still be used, but if
direct access to environ is needed, the _NSGetEnviron() routine, defined in `<crt_externs.h>`, can be
used to retrieve the address of environ at runtime.
